### PR TITLE
Click on truncated identity key to see details.

### PR DESCRIPTION
**Pull request by jonathancross**
Allow user to click on truncated identity key to see full identity.

Explanation:
As a noob, I spent 15 minutes clicking around, reading FAQ, documentation, etc because I couldn't figure out how to get my full address.
This should not require any thought at all.

### CODE REVIEW

**Comment by jonathancross** [comment]
ping @str4d  :-)

**Comment by jonathancross** [comment]
Okay, sad, but giving up...

**Comment by str4d** [comment]
Sorry, I've been very busy with work the past two months, doing no I2P-Bote work, and completely missed this!

Because this GitHub repo is only a mirror, I'll need to manually apply any patch. But I'll review it here first :smiley:

**Comment by jonathancross** [comment]
Oh, good to hear.  Cheers!

**Comment by str4d** [comment]
utACK! I'll try applying it locally and check it works for me.

**Comment by str4d** [comment]
I've merged this! But the Monotone-to-GitHub mirroring script seems to be missing this repository, so it's not showing up yet...

**Comment by str4d** [comment]
I included this in 0.4.4, which has just been released! Unfortunately the Monotone-to-Git gateway is still not working properly, so I'll leave this open for now (because I want to see whether GitHub will auto-close this when it detects the applied patch).

**Comment by jonathancross** [comment]
> I want to see whether GitHub will auto-close this when it detects the applied patch...

Is this still pending?

**Comment by str4d** [comment]
This was merged since time ago, but the git gateway still isn't working :( I am planning to migrate to using git for development however, so once that happens I can push to this repository to update it.

**Pull request closed without merging**
