### PR TITLE
Add eyedeekay to bootstrap peers, remove kytv

### PR DESCRIPTION
**Pull request by eyedeekay**
Just what it says in the title, this change adds the base64 of my permanent node to the bootstrap list and moves kytv's missing node into the commented-out missing nodes list. In the history there are some changes that made me the plugin signer, but I undid them for now. I can try and get rid of them with a rebase if you want.

### CODE REVIEW

**Comment by str4d** [comment]
Yes, please rebase this branch to squash down into a single commit (or two commits - one to comment out kytv, and another to add yourself).

I'm also unfamiliar with this GitHub account. I have verified that there is an `eyedeekay` user in Irc2P that zzz et al interact with, and I see that @mikalv added this account to the I2P GitHub organization 25 days ago. @mikalv, could you please confirm that this is an authentic request to become an I2P-Bote bootstrap node, from the same individual that controls the `eyedeekay` user in Irc2P?

**Comment by eyedeekay** [comment]
Yes it is. I am also u/alreadyburnt on reddit. If you would like I can confirm this using my gpg keys or my SSH keys. I'll squash these down to one commit shortly.

**Comment by eyedeekay** [comment]
So I went to squash those commits, ended up rewriting half the history, reset hard to I could just take the path of least re-create my changes from the current master, and github detected that I had done the hard reset and was the same as the master again and closed my pull request. So I learned something new about github today.

**Comment by mikalv** [comment]
ACK.

**Pull request merged**
